services:
  postgres:
    container_name: interview_task_postgres
    image: postgres:13
    ports:
      - 5590:5432
    environment:
      - POSTGRES_DB=task-dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
