services:
  postgres:
    container_name: interview_task_postgres
    image: postgres:13
    ports:
      - 5590:5432
    environment:
      - POSTGRES_DB=task-dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  
  redis:
    container_name: interview_task_redis
    image: redis:7.0.3-alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
